# Generated by Django 6.0 on 2026-01-04 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='القسم / الجهة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسم مالي',
                'verbose_name_plural': 'الأقسام المالية',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'قبض (استلام)'), ('expense', 'صرف')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='المبلغ (د.ع)')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الوصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.category', verbose_name='الجهة')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
