# Generated by Django 6.0 on 2025-12-20 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_organization_candidatemonitor_badge_issue_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الحزب')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='الرقم التسلسلي')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/', verbose_name='الشعار')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='اللون المميز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حزب سياسي',
                'verbose_name_plural': 'الأحزاب السياسية',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PartyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='الرقم التسلسلي في القائمة')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('voter_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الناخب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='الصورة الشخصية')),
                ('biography', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidacies', to='elections.voter', verbose_name='من سجل الناخبين')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.politicalparty', verbose_name='الحزب')),
            ],
            options={
                'verbose_name': 'مرشح حزب',
                'verbose_name_plural': 'مرشحو الأحزاب',
                'ordering': ['party__serial_number', 'serial_number'],
                'unique_together': {('party', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='PollingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المركز')),
                ('center_number', models.CharField(max_length=20, unique=True, verbose_name='رقم المركز')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('station_count', models.IntegerField(default=1, verbose_name='عدد المحطات في المركز')),
                ('total_registered_voters', models.IntegerField(default=0, verbose_name='إجمالي الناخبين المسجلين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.area', verbose_name='المنطقة/الناحية')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.neighborhood', verbose_name='الحي')),
            ],
            options={
                'verbose_name': 'مركز اقتراع',
                'verbose_name_plural': 'مراكز الاقتراع',
                'ordering': ['center_number'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField(verbose_name='رقم المحطة في المركز')),
                ('full_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='الرقم الكامل للمحطة')),
                ('registered_voters', models.IntegerField(default=0, verbose_name='عدد الناخبين المسجلين')),
                ('total_ballots_received', models.IntegerField(default=0, verbose_name='إجمالي الأوراق المستلمة')),
                ('valid_votes', models.IntegerField(default=0, verbose_name='الأصوات الصحيحة')),
                ('invalid_votes', models.IntegerField(default=0, verbose_name='الأصوات الباطلة')),
                ('counting_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري الجرد'), ('completed', 'مكتمل'), ('issues', 'يوجد مشاكل')], default='pending', max_length=20, verbose_name='حالة الجرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='elections.pollingcenter', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'محطة اقتراع',
                'verbose_name_plural': 'محطات الاقتراع',
                'ordering': ['center__center_number', 'station_number'],
                'unique_together': {('center', 'station_number')},
            },
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0, verbose_name='عدد الأصوات')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='elections.partycandidate', verbose_name='المرشح')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المُدخِل')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='elections.pollingstation', verbose_name='المحطة')),
            ],
            options={
                'verbose_name': 'جرد أصوات',
                'verbose_name_plural': 'جرد الأصوات',
                'ordering': ['-entered_at'],
                'unique_together': {('station', 'candidate')},
            },
        ),
    ]
