# Generated by Django 6.0 on 2025-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_politicalparty_partycandidate_pollingcenter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votecount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='votecount',
            name='vote_type',
            field=models.CharField(choices=[('general', 'تصويت عام'), ('special', 'تصويت خاص')], default='general', max_length=20, verbose_name='نوع التصويت'),
        ),
        migrations.AlterUniqueTogether(
            name='votecount',
            unique_together={('station', 'candidate', 'vote_type')},
        ),
    ]
