# Generated by Django 6.0 on 2025-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_votecount_unique_together_votecount_vote_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenter',
            name='actual_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم الفعلي للمركز'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='card_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المركز في البطاقة'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='governorate',
            field=models.CharField(default='البصرة', max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='registration_center_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم مركز التسجيل'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='registration_center_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم مركز التسجيل'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='voting_type',
            field=models.CharField(choices=[('general', 'اقتراع عام'), ('special', 'اقتراع خاص')], default='general', max_length=20, verbose_name='نوع الاقتراع'),
        ),
    ]
