# Generated by Django 6.0 on 2025-12-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_pollingcenter_actual_name_pollingcenter_card_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernorateHD',
            fields=[
                ('gov_no', models.CharField(db_column='GovNo', max_length=2, primary_key=True, serialize=False)),
                ('gov_name', models.CharField(db_column='GovName', max_length=15, null=True)),
            ],
            options={
                'db_table': 'GovernorateHD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PCHd',
            fields=[
                ('pcno', models.IntegerField(db_column='PCNO', primary_key=True, serialize=False)),
                ('pc_name', models.CharField(db_column='PC_NAME', max_length=70, null=True)),
            ],
            options={
                'db_table': 'PC_HD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonHD',
            fields=[
                ('per_id', models.BigIntegerField(db_column='PER_ID', primary_key=True, serialize=False)),
                ('per_famno', models.BigIntegerField(db_column='PER_FAMNO', null=True)),
                ('per_first', models.CharField(db_column='PER_FIRST', max_length=15, null=True)),
                ('per_father', models.CharField(db_column='PER_FATHER', max_length=15, null=True)),
                ('per_grand', models.CharField(db_column='PER_GRAND', max_length=15, null=True)),
                ('per_dob', models.CharField(db_column='PER_DOB', max_length=10, null=True)),
                ('psno', models.IntegerField(db_column='PSNO', null=True)),
                ('pcno', models.IntegerField(db_column='PCNO', null=True)),
                ('per_vrc_id', models.IntegerField(db_column='VRC_ID', null=True)),
                ('per_gov_id', models.IntegerField(db_column='GOV_MOT_ID', null=True)),
            ],
            options={
                'db_table': 'PersonHD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VrcHD',
            fields=[
                ('vrc_id', models.IntegerField(db_column='VRC_ID', primary_key=True, serialize=False)),
                ('vrc_name_ar', models.CharField(db_column='VRC_NAME_AR', max_length=35, null=True)),
            ],
            options={
                'db_table': 'VRC_HD',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='partycandidate',
            name='stations_not_voted',
            field=models.IntegerField(default=0, verbose_name='محطات لم تصوت'),
        ),
        migrations.AddField(
            model_name='partycandidate',
            name='stations_voted',
            field=models.IntegerField(default=0, verbose_name='محطات صوتت'),
        ),
    ]
