# Generated by Django 6.0 on 2025-12-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_observerregistration_electoralpublic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycandidate',
            name='candidate_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='كود المرشح'),
        ),
    ]
