# Generated by Django 6.0 on 2025-12-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_add_candidate_code_to_partycandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemonitor',
            name='role_type',
            field=models.CharField(choices=[('candidate_observer', 'مراقب مرشح'), ('entity_agent', 'وكيل كيان (مراقب حركة)')], default='candidate_observer', max_length=20, verbose_name='نوع الدور'),
        ),
        migrations.AlterField(
            model_name='candidatemonitor',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='elections.candidate', verbose_name='المرشح'),
        ),
    ]
