# Generated by Django 6.0 on 2025-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_candidatemonitor_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemonitor',
            name='alley',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزقاق'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='education',
            field=models.CharField(choices=[('primary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'إعدادي'), ('diploma', 'دبلوم'), ('bachelors', 'بكالوريوس'), ('masters', 'ماجستير'), ('doctorate', 'دكتوراه'), ('other', 'أخرى')], default='secondary', max_length=20, verbose_name='التحصيل الدراسي'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='face_capture',
            field=models.ImageField(blank=True, null=True, upload_to='monitor_face_captures/', verbose_name='صورة التحقق الحيوي'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='full_address',
            field=models.TextField(blank=True, verbose_name='العنوان الكامل'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب/عزباء'), ('married', 'متزوج/ة'), ('divorced', 'مطلق/ة'), ('widowed', 'أرمل/ة')], default='single', max_length=20, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الأم'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم البطاقة الوطنية'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='nearest_landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='neighborhood_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم المحلة'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='monitor_photos/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='candidatemonitor',
            name='sub_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='الناحية'),
        ),
    ]
