# Generated by Django 6.0 on 2025-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_candidatemonitor_alley_candidatemonitor_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntask',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='المشرف / المكلف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigntask',
            name='target_area',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='الجهة المستهدفة'),
            preserve_default=False,
        ),
    ]
