# Generated by Django 6.0 on 2026-01-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_alter_campaigntask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycandidate',
            name='council_type',
            field=models.CharField(choices=[('parliament', 'مجلس النواب (البرلمان)'), ('provincial', 'مجلس المحافظة')], default='parliament', max_length=20, verbose_name='نوع المجلس'),
        ),
    ]
