# Generated by Django 6.0 on 2026-01-02 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_partycandidate_council_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('supervisor', 'مشرف'), ('data_entry_voters', 'مدخل بيانات الناخبين'), ('data_entry_candidates', 'مدخل بيانات المرشحين'), ('data_entry_monitors', 'مدخل بيانات المراقبين'), ('data_entry_anchors', 'مدخل بيانات المرتكزات'), ('data_entry_introducers', 'مدخل بيانات المعرفين'), ('viewer', 'مستعرض فقط')], default='viewer', max_length=30, verbose_name='الدور الوظيفي')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='يمكنه تصدير التقارير')),
                ('can_delete_records', models.BooleanField(default=False, verbose_name='يمكنه حذف السجلات')),
                ('can_view_sensitive_data', models.BooleanField(default=False, verbose_name='يمكنه عرض البيانات الحساسة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('deactivation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعطيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_area', models.ForeignKey(blank=True, help_text='تحديد منطقة عمل محددة للمستخدم', null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.area', verbose_name='المنطقة المخصصة')),
                ('assigned_neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.neighborhood', verbose_name='الحي المخصص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['user__username'],
            },
        ),
    ]
