# Generated by Django 6.0 on 2026-01-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_merge_candidate_into_partycandidate'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anchor',
            name='anchor_cand_idx',
        ),
        migrations.RemoveIndex(
            model_name='introducer',
            name='intro_anchor_idx',
        ),
        migrations.RemoveIndex(
            model_name='partycandidate',
            name='candidate_party_idx',
        ),
        migrations.RemoveIndex(
            model_name='partycandidate',
            name='candidate_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='profile_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='profile_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='votecount',
            name='vote_station_cand_idx',
        ),
        migrations.RemoveIndex(
            model_name='votecount',
            name='vote_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='voter_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='voter_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='voter_class_idx',
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='voter_intro_idx',
        ),
        migrations.AlterField(
            model_name='anchor',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='elections.candidate', verbose_name='المرشح'),
        ),
        migrations.AlterField(
            model_name='candidatemonitor',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='elections.candidate', verbose_name='المرشح'),
        ),
    ]
