# Generated by Django 6.0 on 2026-01-04 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_remove_anchor_anchor_cand_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رمز الجلسة')),
                ('vote_type', models.CharField(choices=[('general', 'تصويت عام'), ('special', 'تصويت خاص')], default='general', max_length=20, verbose_name='نوع التصويت')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدء الجلسة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الجلسة')),
                ('total_scans', models.IntegerField(default=0, verbose_name='عدد المسحات')),
                ('successful_scans', models.IntegerField(default=0, verbose_name='مسحات ناجحة')),
                ('failed_scans', models.IntegerField(default=0, verbose_name='مسحات فاشلة')),
                ('duplicate_scans', models.IntegerField(default=0, verbose_name='مسحات مكررة')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='حالة الجلسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المُشغِّل')),
            ],
            options={
                'verbose_name': 'جلسة مسح باركود',
                'verbose_name_plural': 'جلسات مسح الباركود',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.TextField(verbose_name='بيانات الباركود الخام')),
                ('barcode_type', models.CharField(blank=True, help_text='مثل: CODE_128, QR_CODE, EAN_13', max_length=50, verbose_name='نوع الباركود')),
                ('center_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المركز المستخرج')),
                ('station_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المحطة المستخرجة')),
                ('vote_type', models.CharField(blank=True, max_length=20, verbose_name='نوع التصويت المستخرج')),
                ('vote_data', models.JSONField(blank=True, help_text='بيانات الأصوات بصيغة JSON', null=True, verbose_name='بيانات الأصوات')),
                ('scan_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاقتراع')),
                ('total_votes', models.IntegerField(blank=True, null=True, verbose_name='إجمالي الأصوات')),
                ('valid_votes', models.IntegerField(blank=True, null=True, verbose_name='أصوات صحيحة')),
                ('invalid_votes', models.IntegerField(blank=True, null=True, verbose_name='أصوات باطلة')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('validated', 'تم التحقق'), ('processed', 'تم المعالجة'), ('rejected', 'مرفوض'), ('duplicate', 'مكرر'), ('error', 'خطأ')], default='pending', max_length=20, verbose_name='الحالة')),
                ('validation_errors', models.TextField(blank=True, verbose_name='أخطاء التحقق')),
                ('validation_warnings', models.TextField(blank=True, verbose_name='تحذيرات التحقق')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المسح')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcode_scans/', verbose_name='صورة الباركود')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_scans', to=settings.AUTH_USER_MODEL, verbose_name='المُشغِّل')),
                ('polling_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_scans', to='elections.pollingcenter', verbose_name='المركز المرتبط')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_scans', to='elections.pollingstation', verbose_name='المحطة المرتبطة')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_scans', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='elections.barcodescansession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'سجل مسح باركود',
                'verbose_name_plural': 'سجلات مسح الباركود',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['center_number', 'station_number'], name='elections_b_center__9b0f78_idx'), models.Index(fields=['status'], name='elections_b_status_06b956_idx'), models.Index(fields=['session', 'scanned_at'], name='elections_b_session_3d2a16_idx')],
            },
        ),
    ]
