# Generated by Django 6.0 on 2026-01-04 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_barcodescansession_barcodescanrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('voter_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الناخب')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='رقم البطاقة الوطنية')),
                ('voting_type', models.CharField(choices=[('general', 'عام'), ('special', 'خاص')], max_length=10, verbose_name='نوع الاقتراع')),
                ('assigned_center_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم المركز الانتخابي')),
                ('assigned_center_name', models.CharField(max_length=200, verbose_name='اسم المركز الانتخابي')),
                ('governorate', models.CharField(default='البصرة', max_length=50, verbose_name='المحافظة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية المهمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مضاف من قبل')),
            ],
            options={
                'verbose_name': 'مدير مركز انتخابي',
                'verbose_name_plural': 'مدراء المراكز الانتخابية',
                'ordering': ['voting_type', 'assigned_center_number'],
            },
        ),
        migrations.AddField(
            model_name='politicalentityagent',
            name='center_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='elections.centerdirector', verbose_name='مدير المركز'),
        ),
        migrations.AddIndex(
            model_name='centerdirector',
            index=models.Index(fields=['voting_type', 'assigned_center_number'], name='elections_c_voting__94788d_idx'),
        ),
        migrations.AddIndex(
            model_name='centerdirector',
            index=models.Index(fields=['status'], name='elections_c_status_a2ca50_idx'),
        ),
    ]
