# Generated by Django manually - Step 2: Add unique constraint

from django.db import migrations, models
from django.db.models import Count


def fix_duplicate_phones(apps, schema_editor):
    """إصلاح أرقام الهواتف المكررة"""
    # Get models
    models_to_fix = [
        ('Voter', 'phone'),
        ('Candidate', 'phone'),
        ('Anchor', 'phone'),
        ('Introducer', 'phone'),
        ('CandidateMonitor', 'phone'),
        ('CenterDirector', 'phone'),
        ('PoliticalEntityAgent', 'phone'),
        ('PartyCandidate', 'phone'),
        ('CivilSocietyObserver', 'phone'),
        ('InternationalObserver', 'phone'),
        ('ObserverRegistration', 'phone_number'),
    ]
    
    for model_name, field_name in models_to_fix:
        Model = apps.get_model('elections', model_name)
        
        # Find duplicates
        duplicates = (Model.objects
                      .exclude(**{f"{field_name}__isnull": True})
                      .values(field_name)
                      .annotate(count=Count('id'))
                      .filter(count__gt=1))
        
        for dup in duplicates:
            phone = dup[field_name]
            records = list(Model.objects.filter(**{field_name: phone}).order_by('id'))
            
            # Keep first, modify others
            for i, record in enumerate(records):
                if i > 0:
                    new_phone = f"{phone}-{i}"
                    setattr(record, field_name, new_phone)
                    record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0019_add_null_to_phone'),
    ]

    operations = [
        # Fix duplicates first
        migrations.RunPython(fix_duplicate_phones, reverse_code=migrations.RunPython.noop),
        
        # Add unique constraint
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidatemonitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='centerdirector',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='politicalentityagent',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='partycandidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='civilsocietyobserver',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='internationalobserver',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='observerregistration',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
