# Generated by Django 6.0 on 2026-01-05 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_add_unique_to_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerdirector',
            name='assigned_center_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='رقم المركز الانتخابي'),
        ),
        migrations.AddConstraint(
            model_name='centerdirector',
            constraint=models.UniqueConstraint(fields=('voting_type', 'assigned_center_number'), name='unique_center_per_voting_type'),
        ),
    ]
