# Generated by Django 6.0 on 2026-01-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0021_alter_centerdirector_assigned_center_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('agent', 'وكيل كيان سياسي'), ('monitor', 'مراقب مرشح')], max_length=10, verbose_name='نوع السجل')),
                ('status', models.CharField(choices=[('checked_in', 'حضر'), ('checked_out', 'انصرف')], max_length=15, verbose_name='الحالة')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت تسجيل الدخول')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تسجيل دخول مدير',
                'verbose_name_plural': 'سجلات تسجيل دخول المدراء',
                'ordering': ['-login_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='centerdirector',
            name='unique_center_per_voting_type',
        ),
        migrations.AddField(
            model_name='centerdirector',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='centerdirector',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_directors', to=settings.AUTH_USER_MODEL, verbose_name='مضاف من قبل'),
        ),
        migrations.AlterField(
            model_name='centerdirector',
            name='assigned_center_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم المركز الانتخابي'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='elections.politicalentityagent', verbose_name='الوكيل'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='elections.candidatemonitor', verbose_name='المراقب'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='elections.centerdirector', verbose_name='سجل بواسطة'),
        ),
        migrations.AddField(
            model_name='directorloginlog',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='elections.centerdirector', verbose_name='مدير المركز'),
        ),
        migrations.AddField(
            model_name='directorloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['record_type', 'status'], name='elections_a_record__778220_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-created_at'], name='elections_a_created_460c27_idx'),
        ),
    ]
