# Generated by Django 6.0 on 2026-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0022_add_director_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('supervisor', 'مشرف'), ('data_entry_voters', 'مدخل بيانات الناخبين'), ('data_entry_candidates', 'مدخل بيانات المرشحين'), ('data_entry_monitors', 'مدخل بيانات المراقبين'), ('data_entry_anchors', 'مدخل بيانات المرتكزات'), ('data_entry_introducers', 'مدخل بيانات المعرفين'), ('data_entry_results', 'مدخل نتائج الانتخابات'), ('viewer', 'مستعرض فقط')], default='viewer', max_length=30, verbose_name='الدور الوظيفي'),
        ),
    ]
