# Generated by Django 6.0 on 2026-01-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0024_alter_votecount_entered_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoralpublic',
            options={'ordering': ['-registered_at'], 'verbose_name': 'مرتكز', 'verbose_name_plural': 'المرتكزات'},
        ),
        migrations.AlterUniqueTogether(
            name='electoralpublic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electoralpublic',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchors_support', to='elections.partycandidate', verbose_name='المرشح'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='password',
            field=models.CharField(help_text='كلمة مرور للدخول إلى النظام', max_length=128, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='phone_number',
            field=models.CharField(help_text='مثال: 07XXXXXXXXX', max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الناخب'),
        ),
        migrations.RemoveField(
            model_name='electoralpublic',
            name='linked_anchor',
        ),
        migrations.RemoveField(
            model_name='electoralpublic',
            name='linked_candidate',
        ),
        migrations.RemoveField(
            model_name='electoralpublic',
            name='linked_introducer',
        ),
        migrations.RemoveField(
            model_name='electoralpublic',
            name='reference_code',
        ),
    ]
