# Generated by Django 6.0 on 2026-01-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_alter_electoralpublic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalvoterrecord',
            options={'ordering': ['-added_at'], 'verbose_name': 'معرف', 'verbose_name_plural': 'المعرفين'},
        ),
        migrations.AlterUniqueTogether(
            name='personalvoterrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='personalvoterrecord',
            name='anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='introducers', to='elections.electoralpublic', verbose_name='المرتكز'),
        ),
        migrations.AddField(
            model_name='personalvoterrecord',
            name='anchor_code',
            field=models.CharField(blank=True, help_text='كود المرتكز للربط به', max_length=50, verbose_name='كود المرتكز'),
        ),
        migrations.AlterField(
            model_name='personalvoterrecord',
            name='classification',
            field=models.CharField(choices=[('supporter', 'مؤيد'), ('neutral', 'محايد'), ('opponent', 'معارض'), ('unknown', 'غير محدد')], default='supporter', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='personalvoterrecord',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='personalvoterrecord',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الناخب'),
        ),
        migrations.RemoveField(
            model_name='personalvoterrecord',
            name='owner',
        ),
        migrations.CreateModel(
            name='IntroducerVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_number', models.CharField(max_length=50, verbose_name='رقم الناخب')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('voting_center_name', models.CharField(blank=True, max_length=150, verbose_name='اسم مركز الاقتراع')),
                ('voting_center_number', models.CharField(blank=True, max_length=50, verbose_name='رقم مركز الاقتراع')),
                ('registration_center_name', models.CharField(blank=True, max_length=150, verbose_name='اسم مركز التسجيل')),
                ('registration_center_number', models.CharField(blank=True, max_length=50, verbose_name='رقم مركز التسجيل')),
                ('station_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المحطة')),
                ('family_number', models.CharField(blank=True, max_length=50, verbose_name='رقم العائلة')),
                ('governorate', models.CharField(default='البصرة', max_length=50, verbose_name='المحافظة')),
                ('classification', models.CharField(choices=[('supporter', 'مؤيد'), ('neutral', 'محايد'), ('opponent', 'معارض'), ('unknown', 'غير محدد')], default='supporter', max_length=20, verbose_name='التصنيف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='elections.personalvoterrecord', verbose_name='المعرف')),
            ],
            options={
                'verbose_name': 'ناخب معرف',
                'verbose_name_plural': 'ناخبين المعرفين',
                'ordering': ['-added_at'],
                'unique_together': {('introducer', 'voter_number')},
            },
        ),
    ]
