# Generated by Django 6.0 on 2026-01-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_alter_personalvoterrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observerregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'تسجيل مراقب/وكيل', 'verbose_name_plural': 'تسجيلات المراقبين والوكلاء'},
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='alley',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='linked_anchor',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='monitoring_center_name',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='monitoring_center_number',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='nearest_landmark',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='neighborhood_number',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='observerregistration',
            name='sub_district',
        ),
        migrations.AddField(
            model_name='observerregistration',
            name='candidate_code',
            field=models.CharField(blank=True, help_text='يتم ملؤه فقط للمراقبين', max_length=50, verbose_name='كود المرشح'),
        ),
        migrations.AddField(
            model_name='observerregistration',
            name='observer_type',
            field=models.CharField(choices=[('candidate_monitor', 'مراقب مرشح'), ('entity_agent', 'وكيل كيان سياسي')], default='candidate_monitor', max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='observerregistration',
            name='linked_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observer_registrations', to='elections.partycandidate', verbose_name='المرشح المرتبط'),
        ),
    ]
