# Generated by Django 6.0 on 2026-01-07 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('elections', '0027_alter_observerregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل اتصال', 'verbose_name_plural': 'سجلات الاتصالات'},
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='result',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='voter',
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='call_status',
            field=models.CharField(choices=[('answered', 'تم الرد'), ('busy', 'مشغول'), ('no_answer', 'لا يوجد رد'), ('wrong_number', 'رقم خاطئ'), ('switched_off', 'مغلق'), ('later', 'طلب الاتصال لاحقاً')], max_length=20, null=True, verbose_name='حالة الاتصال'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='caller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المتصل'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='outcome',
            field=models.TextField(blank=True, verbose_name='نتيجة الاتصال'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['content_type', 'object_id'], name='elections_c_content_d5e21c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['created_at'], name='elections_c_created_b4e5e9_idx'),
        ),
    ]
