# Generated by Django 6.0 on 2026-01-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0028_alter_communicationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centerdirector',
            name='director_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='كود المدير'),
        ),
        migrations.AddField(
            model_name='politicalentityagent',
            name='agent_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='كود الوكيل'),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='introducer_code',
            field=models.CharField(blank=True, editable=False, max_length=60, null=True, unique=True, verbose_name='كود المعرف'),
        ),
        migrations.CreateModel(
            name='SubOperationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='كود الغرفة')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الغرفة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'غرفة عمليات فرعية',
                'verbose_name_plural': 'غرف العمليات الفرعية',
                'ordering': ['room_code'],
            },
        ),
        migrations.AddField(
            model_name='anchor',
            name='sub_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchors', to='elections.suboperationroom', verbose_name='غرفة العمليات'),
        ),
        migrations.AddField(
            model_name='centerdirector',
            name='sub_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='elections.suboperationroom', verbose_name='غرفة العمليات'),
        ),
        migrations.AddField(
            model_name='introducer',
            name='sub_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introducers', to='elections.suboperationroom', verbose_name='غرفة العمليات'),
        ),
        migrations.AddField(
            model_name='politicalentityagent',
            name='sub_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='elections.suboperationroom', verbose_name='غرفة العمليات'),
        ),
    ]
