# Generated by Django 6.0 on 2026-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_barcodescanrecord_unique_constraints'),
        ('elections', '0029_centerdirector_director_code_and_more'),
    ]

    operations = [
    ]
