# Generated by Django 6.0 on 2026-01-09 18:10

import django.db.models.deletion
import elections.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0030_merge_20260109_1643'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='barcodescanrecord',
            name='unique_validated_station_scan',
        ),
        migrations.RemoveIndex(
            model_name='barcodescanrecord',
            name='idx_scan_center_station',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linked_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.candidate', verbose_name='المرشح المرتبط'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linked_operations_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.suboperationroom', verbose_name='غرفة العمليات المرتبطة'),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='candidatemonitor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidatemonitor',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='centerdirector',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='civilsocietyobserver',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='civilsocietyobserver',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='phone_number',
            field=models.CharField(help_text='مثال: 07XXXXXXXXX', max_length=11, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='electoralpublic',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='internationalobserver',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='introducervoter',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='observerregistration',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='observerregistration',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='personalvoterrecord',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='personalvoterrecord',
            name='voter_number',
            field=models.CharField(max_length=50, unique=True, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='politicalentityagent',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='politicalentityagent',
            name='voter_number',
            field=models.CharField(max_length=50, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('supervisor', 'مشرف'), ('data_entry_voters', 'مدخل بيانات الناخبين'), ('data_entry_candidates', 'مدخل بيانات المرشحين'), ('data_entry_monitors', 'مدخل بيانات المراقبين'), ('data_entry_anchors', 'مدخل بيانات المرتكزات'), ('data_entry_introducers', 'مدخل بيانات المعرفين'), ('data_entry_results', 'مدخل نتائج الانتخابات'), ('viewer', 'مستعرض فقط'), ('candidate', 'مرشح'), ('technical_support', 'دعم فني'), ('operations_room', 'غرفة عمليات')], default='viewer', max_length=30, verbose_name='الدور الوظيفي'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
    ]
