# Generated by Django 6.0 on 2026-01-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0031_remove_barcodescanrecord_unique_validated_station_scan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مركز التسجيل')),
                ('center_number', models.CharField(max_length=20, unique=True, verbose_name='رقم مركز التسجيل')),
                ('governorate', models.CharField(default='البصرة', max_length=50, verbose_name='المحافظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مركز تسجيل',
                'verbose_name_plural': 'مراكز التسجيل',
                'ordering': ['center_number'],
            },
        ),
        migrations.AddField(
            model_name='voter',
            name='polling_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='elections.pollingcenter', verbose_name='مركز الاقتراع (مرتبط)'),
        ),
        migrations.AddField(
            model_name='voter',
            name='polling_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters_list', to='elections.pollingstation', verbose_name='المحطة (مرتبطة)'),
        ),
        migrations.AddField(
            model_name='pollingcenter',
            name='registration_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_centers', to='elections.registrationcenter', verbose_name='مركز التسجيل'),
        ),
        migrations.AddField(
            model_name='voter',
            name='registration_center_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='elections.registrationcenter', verbose_name='مركز التسجيل (مرتبط)'),
        ),
    ]
