# Generated by Django 6.0 on 2026-01-15 04:35

import elections.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0032_registrationcenter_voter_polling_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
    ]
