# Generated by Django 6.0 on 2026-01-07 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0022_add_director_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المجلد')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='archive.archivefolder', verbose_name='المجلد الأب')),
            ],
            options={
                'verbose_name': 'مجلد أرشيف',
                'verbose_name_plural': 'مجلدات الأرشيف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, help_text='PDF أو Word', null=True, upload_to='candidates/cv/%Y/', verbose_name='السيرة الذاتية (CV)')),
                ('personal_photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='الصورة الشخصية')),
                ('campaign_photo', models.ImageField(blank=True, null=True, upload_to='candidates/campaign/', verbose_name='صورة الحملة الانتخابية')),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='candidates/documents/id/', verbose_name='نسخة الهوية')),
                ('certificate_of_good_conduct', models.FileField(blank=True, null=True, upload_to='candidates/documents/conduct/', verbose_name='شهادة حسن السيرة والسلوك')),
                ('educational_certificates', models.FileField(blank=True, null=True, upload_to='candidates/documents/education/', verbose_name='الشهادات الدراسية')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='candidates/documents/other/', verbose_name='وثائق أخرى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='elections.candidate', verbose_name='المرشح')),
            ],
            options={
                'verbose_name': 'وثيقة مرشح',
                'verbose_name_plural': 'وثائق المرشحين',
                'ordering': ['candidate__full_name'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان النموذج')),
                ('category', models.CharField(choices=[('official_letters', 'كتب رسمية'), ('reports', 'تقارير'), ('forms', 'استمارات'), ('certificates', 'شهادات'), ('agreements', 'اتفاقيات وعقود'), ('requests', 'طلبات'), ('notifications', 'تعاميم وإشعارات'), ('financial', 'نماذج مالية'), ('other', 'أخرى')], max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='templates/forms/', verbose_name='الملف')),
                ('file_type', models.CharField(editable=False, max_length=20, verbose_name='نوع الملف')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='الإصدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('download_count', models.IntegerField(default=0, verbose_name='عدد مرات التحميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نموذج جاهز',
                'verbose_name_plural': 'النماذج والفورمات الجاهزة',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category'], name='archive_for_categor_d26376_idx'), models.Index(fields=['is_active'], name='archive_for_is_acti_723b46_idx')],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=20, verbose_name='نوع الكتاب')),
                ('letter_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الكتاب')),
                ('letter_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الكتاب')),
                ('from_entity', models.CharField(blank=True, max_length=300, verbose_name='الجهة المرسلة')),
                ('to_entity', models.CharField(blank=True, max_length=300, verbose_name='الجهة المستقبلة')),
                ('subject', models.CharField(max_length=500, verbose_name='الموضوع')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل/الملاحظات')),
                ('attachment', models.FileField(blank=True, help_text='PDF, Word, صور', null=True, upload_to='letters/%Y/%m/', verbose_name='المرفقات')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('important', 'مهم'), ('urgent', 'عاجل'), ('very_urgent', 'عاجل جداً')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('archived', 'مؤرشف')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب الواردة والصادرة',
                'ordering': ['-letter_date', '-created_at'],
                'indexes': [models.Index(fields=['-letter_date'], name='archive_let_letter__e966e4_idx'), models.Index(fields=['letter_type'], name='archive_let_letter__a6b95d_idx'), models.Index(fields=['status'], name='archive_let_status_7b8308_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الوثيقة')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الوثيقة')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الوثيقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='archive/%Y/%m/', verbose_name='الملف')),
                ('tags', models.CharField(blank=True, help_text='افصل بين الكلمات بفاصلة', max_length=500, verbose_name='الكلمات المفتاحية')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأرشفة')),
                ('archived_by', models.CharField(blank=True, max_length=100, verbose_name='أرشفه')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='archive.archivefolder', verbose_name='المجلد')),
            ],
            options={
                'verbose_name': 'وثيقة مؤرشفة',
                'verbose_name_plural': 'الوثائق المؤرشفة',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['-archived_at'], name='archive_arc_archive_914279_idx'), models.Index(fields=['document_type'], name='archive_arc_documen_d789cd_idx')],
            },
        ),
    ]
