# Generated by Django 6.0 on 2026-01-07 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_order', models.IntegerField(blank=True, null=True, verbose_name='تسلسل المرشح داخل القائمة')),
                ('voter_id', models.CharField(max_length=20, verbose_name='رقم الناخب')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم المرشح')),
                ('grandfather4_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الجد الرابع')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='اللقب')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الام')),
                ('mother_father_name', models.CharField(blank=True, max_length=100, verbose_name='اسم اب الام')),
                ('mother_grandfather_name', models.CharField(blank=True, max_length=100, verbose_name='اسم جد الام')),
                ('mother_surname', models.CharField(blank=True, max_length=100, verbose_name='لقب الام')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='محل التولد')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التولد')),
                ('governorate', models.CharField(default='البصرة', max_length=100, verbose_name='المحافظة')),
                ('qada', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('nahia', models.CharField(blank=True, max_length=100, verbose_name='الناحية')),
                ('mahalla', models.CharField(blank=True, max_length=50, verbose_name='المحلة')),
                ('zukak', models.CharField(blank=True, max_length=50, verbose_name='الزقاق')),
                ('dar', models.CharField(blank=True, max_length=50, verbose_name='الدار')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='التحصيل الدراسي')),
                ('cert_number', models.CharField(blank=True, max_length=50, verbose_name='رقم وثيقة التخرج')),
                ('cert_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار التأييد')),
                ('cert_issuer', models.CharField(blank=True, max_length=150, verbose_name='جهة الإصدار')),
                ('national_id_number', models.CharField(blank=True, max_length=50, verbose_name='رقم البطاقة الموحدة')),
                ('national_id_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار البطاقة الموحدة')),
                ('ballot_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم في ورقة الاقتراع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'استمارة معلومات مرشح',
                'verbose_name_plural': 'استمارات معلومات المرشحين',
                'ordering': ['ticket_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200, verbose_name='اسم المرشح')),
                ('interview_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المقابلة')),
                ('interviewer', models.CharField(max_length=150, verbose_name='القائم بالمقابلة')),
                ('appearance_score', models.IntegerField(default=0, verbose_name='المظهر العام (10)')),
                ('charisma_score', models.IntegerField(default=0, verbose_name='الكاريزما والحضور (10)')),
                ('speaking_score', models.IntegerField(default=0, verbose_name='اللباقة والقدرة على التحدث (10)')),
                ('cultural_score', models.IntegerField(default=0, verbose_name='المستوى الثقافي (10)')),
                ('political_awareness', models.IntegerField(default=0, verbose_name='الوعي السياسي (10)')),
                ('community_influence', models.IntegerField(default=0, verbose_name='التأثير الاجتماعي (10)')),
                ('loyalty_score', models.IntegerField(default=0, verbose_name='الولاء والالتزام (10)')),
                ('financial_capability', models.IntegerField(default=0, verbose_name='المقدرة المالية للدعاية (10)')),
                ('strength_points', models.TextField(blank=True, verbose_name='نقاط القوة')),
                ('weakness_points', models.TextField(blank=True, verbose_name='نقاط الضعف')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة'), ('accepted', 'مقبول أولياً'), ('rejected', 'مرفوض'), ('reserve', 'احتياط')], default='pending', max_length=20, verbose_name='القرار النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استمارة مقابلة',
                'verbose_name_plural': 'استمارات المقابلات',
                'ordering': ['-interview_date'],
            },
        ),
    ]
