# Generated by Django 6.0 on 2026-01-09 18:10

import elections.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_candidateinfoform_candidateinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfoform',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[elections.validators.validate_phone_number], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidateinfoform',
            name='voter_id',
            field=models.CharField(max_length=20, validators=[elections.validators.validate_voter_number_required], verbose_name='رقم الناخب'),
        ),
    ]
