# Generated by Django 6.0 on 2026-01-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_candidateinfoform_phone_number_and_more'),
        ('elections', '0032_registrationcenter_voter_polling_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='elections.partycandidate', verbose_name='المرشح'),
        ),
    ]
