# Generated by Django 6.0 on 2026-01-13 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_candidatedocument_candidate'),
        ('elections', '0032_registrationcenter_voter_polling_center_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'وثيقة مرشح', 'verbose_name_plural': 'وثائق المرشحين'},
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='manual_candidate_name',
            field=models.CharField(blank=True, help_text='املأ هذا الحقل إذا لم يكن المرشح موجوداً في القائمة', max_length=200, null=True, verbose_name='اسم المرشح (يدوي)'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='elections.partycandidate', verbose_name='المرشح'),
        ),
    ]
