"""
Django settings for electoral_office project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@z_(zqnz11&19e9=1c*b8fvaekk_gs=6*)($x^a$sx@pyl2o88'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.0.123', '192.168.0.*', '*']

# CSRF Settings - Updated for ngrok and external access
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://*.ngrok-free.app',  # Support for ngrok
    'https://*.ngrok.io',  # Legacy ngrok domains
    'http://*.ngrok-free.app',  # HTTP ngrok (for testing)
    'http://*.ngrok.io',  # HTTP legacy ngrok
    'https://*.loca.lt',  # LocalTunnel HTTPS
    'http://*.loca.lt',  # LocalTunnel HTTP
    'https://*.trycloudflare.com',  # Cloudflare Tunnel HTTPS
    'http://*.trycloudflare.com',  # Cloudflare Tunnel HTTP (for testing)
]

# For development only - allow CSRF from any origin
# Remove or set to False in production
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

# Session Settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'elections',
    'finance',
    'archive',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
]

# ==================== Performance Optimization ====================

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'electoral-office-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Cache dashboard statistics for 5 minutes
DASHBOARD_CACHE_TIMEOUT = 300  # 5 minutes

# Session Configuration (Performance)
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Database Query Optimization
# Connection pooling
CONN_MAX_AGE = 600  # 10 minutes
CONN_HEALTH_CHECKS = True

# Debug Toolbar (Development only)
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Compression for better performance
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'electoral_office.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'elections.decorators.user_profile_context',  # Add user profile context
            ],
        },
    },
]

WSGI_APPLICATION = 'electoral_office.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            'init_command': "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=-64000; PRAGMA temp_store=MEMORY;",
        },
    },
    'legacy_voters_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(r'C:\Users\2025\.gemini\antigravity\scratch\voters_decrypted_fast.sqlite'),
        'OPTIONS': {
            'timeout': 30,
        },
    }
}

# Database connection caching
CONN_MAX_AGE = 600
CONN_HEALTH_CHECKS = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Baghdad'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
